name: 'dbt_learn_repos'
version: '1.0.0'

profile: 'dbt_learn_repos'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_learn_repos:
    +materialized: view


seeds:
  dbt_learn_repos:
    +column_types:
      EMPLOYEE_ID: number
      EMPLOYEE_NAME: text
      DEPARTMENT: text
